### ISSUE TITLE
Can't install with in AAPANEL

### ISSUE THREAD

**Issue by GenzPN** [Kaishiyoku/manga-organizer#104]
Hi i use AAPANEL to install manga but i still have error when i install
Command: composer install --no-dev --no-scripts
```
PHP Fatal error:  Uncaught Error: Call to undefined function Composer\XdebugHandler\putenv() in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php:97
Stack trace:
#0 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Status.php(59): Composer\XdebugHandler\Process::setEnv()
#1 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php(101): Composer\XdebugHandler\Status->__construct()
#2 phar:///usr/bin/composer/bin/composer(23): Composer\XdebugHandler\XdebugHandler->__construct()
#3 /usr/bin/composer(29): require('...')
#4 {main}
  thrown in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 97

Fatal error: Uncaught Error: Call to undefined function Composer\XdebugHandler\putenv() in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php:97
Stack trace:
#0 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Status.php(59): Composer\XdebugHandler\Process::setEnv()
#1 phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/XdebugHandler.php(101): Composer\XdebugHandler\Status->__construct()
#2 phar:///usr/bin/composer/bin/composer(23): Composer\XdebugHandler\XdebugHandler->__construct()
#3 /usr/bin/composer(29): require('...')
#4 {main}
  thrown in phar:///usr/bin/composer/vendor/composer/xdebug-handler/src/Process.php on line 97
```

**Comment by Kaishiyoku** [comment]
Hello, thanks for submitting. I will take a look into this as soon as I can.

Which version of PHP are you using?

**Comment by GenzPN** [comment]
I use PHP 8.0.26
![image](https://user-images.githubusercontent.com/39546317/222035235-6118e79f-0e5d-4697-bda5-f3f238759685.png)

**Comment by Kaishiyoku** [comment]
It looks like the putenv function has been disabled with aaPanel. You should be able to enable it at "Disabled functions".

I could reproduce the exception with disabling the `putenv` function in the php.ini file.

https://forum.aapanel.com/d/3299-composer-error/3

**Comment by GenzPN** [comment]
```
root@genzpn:/www/wwwroot/manga.genzpn.com# /www/server/php/80/bin/php artisan user:create

   ERROR  There are no commands defined in the "user" namespace.

root@genzpn:/www/wwwroot/manga.genzpn.com#
```

I have suck when i create user

**Comment by Kaishiyoku** [comment]
Ah, I have renamed the command some time ago...I forgot to adjust the README accordingly.

The new command is as follows:

`php artisan make:user`

**Comment by GenzPN** [comment]
So yeah now i can create new user but got a new error
```
root@genzpn:~# cd /www/wwwroot/manga.genzpn.com
root@genzpn:/www/wwwroot/manga.genzpn.com# npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'laravel-vite-plugin@0.7.2',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'postcss-import@15.1.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@3.7.4',
npm WARN EBADENGINE   required: { node: '>=14.18.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite@4.0.2',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 100 packages in 3s

19 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
root@genzpn:/www/wwwroot/manga.genzpn.com# 
```
Ah so this is some error in npm ??

**Comment by Kaishiyoku** [comment]
Yes. Some npm packages require Nodejs 14 or higher. The latest LTS version of Nodejs is 18. I would recommend to update Nodejs to version 18.
